services:
  - type: web
    name: facebook-tracker-bot
    env: python
    pythonVersion: 3.11
    buildCommand: pip install -r requirements.txt
    startCommand: cd app && python main.py
    envVars:
      - key: FB_EMAIL
      - key: FB_PASSWORD
      - key: TELEGRAM_BOT_TOKEN
      - key: PORT
        value: 10000
